name: ci

on: [ push, pull_request ]

jobs:
 lint:
  runs-on: ubuntu-latest
  steps:
  - name: Checkout
    uses: actions/checkout@v2
  - name: Set up Python 3.9
    uses: actions/setup-python@v2
    with:
     python-version: 3.9
  - run: pip install flake8
  - run: flake8 run.py core
 test:
  runs-on: ubuntu-latest
  container:
   image: nvidia/cuda:11.8.0-devel-ubuntu22.04
  strategy:
   matrix:
    include:
    - name: CPU
      run: ./run.py -f=.github/examples/face.jpg -t=.github/examples/target.mp4 -o=.github/examples/output.mp4
    - name: GPU
      run: ./run.py -f=.github/examples/face.jpg -t=.github/examples/target.mp4 -o=.github/examples/output.mp4 --gpu-vendor=nvidia
  steps:
  - name: Checkout
    uses: actions/checkout@v2
  - name: Install dependencies
    run: |
        apt-get update
        apt-get install -y ffmpeg python3-pip
        pip install --upgrade pip
  - run: pip install -r requirements.txt gdown
  - run: gdown 13QpWFWJ37EB-nHrEOY64CEtQWY-tz7DZ
  - run: ${{ matrix.run }}
  - run: ffmpeg -i .github/examples/snapshot.mp4 -i .github/examples/output.mp4 -filter_complex "psnr" -f null -

