name: ci

on: [ push, pull_request ]

jobs:
 lint:
  runs-on: ubuntu-latest
  steps:
  - name: Checkout
    uses: actions/checkout@v2
  - name: Set up Python 3.9
    uses: actions/setup-python@v2
    with:
     python-version: 3.9
  - run: pip install flake8
  - run: flake8 run.py core
 test:
  runs-on: ubuntu-latest
  strategy:
   matrix:
    include:
    - name: CPU
      args: -f=.github/examples/face.jpg -t=.github/examples/target.mp4 -o=.github/examples/output.mp4
    - name: GPU
      args: -f=.github/examples/face.jpg -t=.github/examples/target.mp4 -o=.github/examples/output.mp4 --gpu-vendor=nvidia
  steps:
  - name: Checkout
    uses: actions/checkout@v2
  - name: Set up ffmpeg
    uses: FedericoCarboni/setup-ffmpeg@v2
  - name: Set up Python 3.9
    uses: actions/setup-python@v2
    with:
     python-version: 3.9
  - uses: Jimver/cuda-toolkit@v0.2.10
    with:
     cuda: '11.8.0'
  - run: pip install -r requirements.txt
  - run: pip install gdown
  - run: gdown 13QpWFWJ37EB-nHrEOY64CEtQWY-tz7DZ
  - run: ./run.py {{ matrix.args }}
  - run: ffmpeg -i .github/examples/snapshot.mp4 -i .github/examples/output.mp4 -filter_complex "psnr" -f null -

